### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by alexgleason** [rveilleux/ard-drivin#1]
Hi, I'm currently in the process of adding license info to all the games in [Erwin's Arduboy repo](http://arduboy.ried.cl/) so people can easily filter out proprietary games. Would you be willing to add an [open source license](https://choosealicense.com/) to your project so I can tag it as an open source game in the repo?

Thanks!

**Comment by rveilleux** [comment]
Hi Alex,

yes sure. Do you need me to do it? Or can you add it yourself?

Rem.

**Comment by alexgleason** [comment]
Hi @rveilleux, if you add a file to the root of this repo (usually called `LICENSE`) containing the text of the license you'd like to use, I can update Erwin's repo to reflect the license you chose. Here are some common license options: https://choosealicense.com/

Alex

**Comment by rveilleux** [comment]
Hello again Alex,

the deed is done: LICENSE.txt added. It is an MIT License.

Thank you!

**Comment by alexgleason** [comment]
Awesome, thanks!
